# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-18 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_axf_mainshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axf_mainshow',
            name='longname2',
            field=models.CharField(max_length=200),
        ),
    ]
