# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-18 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20180818_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='axf_goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=20)),
                ('productimg', models.CharField(max_length=200)),
                ('productname', models.CharField(max_length=100)),
                ('productlongname', models.CharField(max_length=100)),
                ('isxf', models.IntegerField(default=0)),
                ('pmdesc', models.IntegerField(default=0)),
                ('specifics', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('marketprice', models.DecimalField(decimal_places=6, max_digits=8)),
                ('categoryid', models.IntegerField()),
                ('childcid', models.IntegerField()),
                ('childcidname', models.CharField(max_length=20)),
                ('dealerid', models.CharField(max_length=20)),
                ('storenums', models.IntegerField(default=200)),
                ('productnum', models.IntegerField(default=3)),
            ],
            options={
                'db_table': 'axf_goods',
            },
        ),
    ]
