# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-18 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_axf_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axf_goods',
            name='marketprice',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='axf_goods',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
