# Generated by Django 2.0.8 on 2018-08-23 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20180821_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axf_shopcar',
            name='goodsid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.axf_goods'),
        ),
        migrations.AlterField(
            model_name='axf_shopcar',
            name='memberid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.member'),
        ),
        migrations.AlterModelTable(
            name='axf_shopcar',
            table='axf_shopcar',
        ),
    ]
